export const queryKeys = {
  profile: ['profile'] as const,
  partnerProfile: ['partner-profile'] as const,
  draft: (date: string) => ['planner-draft', date] as const,
  initialPlan: (date: string) => ['initial-plan', date] as const,
  currentPlan: (date: string) => ['current-plan', date] as const,
  partnerCurrentPlan: (date: string) => ['partner-current-plan', date] as const,
  mySubmission: (date: string) => ['my-submission', date] as const,
  partnerSubmission: ['partner-submission'] as const,
  pendingReviews: ['pending-reviews'] as const,
  reports: ['reports'] as const,
  userStats: ['user-stats'] as const,
  achievements: ['achievements'] as const,
  notifications: ['notifications'] as const,
  unreadNotificationsCount: ['notifications', 'unread-count'] as const,
  statsPartnerId: ['stats-partner-id'] as const,
  statsUserStats: (userId: string) => ['stats-user-stats', userId] as const,
  statsAchievements: (userId: string) => ['stats-achievements', userId] as const,
  journey: (userId: string) => ['journey', userId] as const,
  journeyMilestones: (journeyId: string) => ['journey-milestones', journeyId] as const,
  mascotFeed: ['mascot-feed'] as const,
  mascotUnread: ['mascot-unread'] as const,
};
